services:
  stream-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepfake-voice-stream-server
    volumes:
      - ./assets:/app/assets
    ports:
      - "13000:13000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
